### ISSUE TITLE
read-only raspberry 

### ISSUE THREAD

**Issue by roccopietrini** [colloqi/piSignage#133]
Hi,
Has anyone experience on making the raspberry read-only ? I would like to do this to minimize SD card corruption issues..

**Comment by hitesh83** [comment]
Pisignage images are very lite on sd card,  we are running it almost 18hr daily for past 3 years in 100+ installation.
Till date haven't face any SD card issue.

As we keep changing our content every alternate day, making SD read only is not a good idea for us. 

For small local install with no change in content, read only should work.

**Comment by roccopietrini** [comment]
Do you schedule poweroff / poweron on the raspberry everyday? It is my understanding that incorrect poweroff can damage the SD card (can I also ask if you recommend a card vendor?)..Thx

**Comment by hitesh83** [comment]
We do not schedule ON / OFF in Raspberry pi,
ON/OFF is controlled through a timer installed in the power distribution box.
SD card may get damaged due to incorrect power off, but due to very low read-write operations, things are still good for us.

Mostly we used SanDisk Class 10.

![image](https://user-images.githubusercontent.com/15059079/104435624-98bd1400-55b2-11eb-8143-a6ae39432123.png)

**Comment by roccopietrini** [comment]
Thanks! Just to confirm.. you don't shutdown the raspberry (with shutdown or poweroff command in raspbian) before the power loss.. is that correct ?

**Comment by hitesh83** [comment]
yes, your understanding is correct, 
actually, it is not the correct way for RPi, but digital signages need to run like this, and we are ready to replace the SD cards when it fails.
And there are many if and but in running a script on time to shut down, so we are taking the risk.
