### ISSUE TITLE
Multiple zones layout display issues

### ISSUE THREAD

**Issue by JDL747** [colloqi/piSignage#34]
Hi,

It seems that there are some issues when using multiple zones layout and in my case, the `3a: Three Zones(full bottom) with Main Zone on right`: 

**Issue 1**: If I don't select `Stretch images to the screen` in the group settings, the image don't fit the space despite its resolution respect the zone dimension `(Side Zone: 320x540, Bottom Zone: 1280x180)`

[Screenshot](https://drive.google.com/file/d/0B4_yTbDkJlCaMEg2UVpiczBTRk0/view?usp=sharing)

**Issue 2**:  There is a delay of about 2s before the `side and bottom zones` appeared on the first cycle and it seems that there is box-shadow on the `side and bottom zones` which doesn't look nice.

[Video](https://drive.google.com/file/d/0B4_yTbDkJlCaRkl6NkhKVFVtblE/view?usp=sharing)

**Issue 3**:  After the first cycle, the `side and bottom zones` don't show the assets anymore. It's only a black zone.

[Video](https://drive.google.com/file/d/0B4_yTbDkJlCaQVNmMHdyM0Q5SEk/view?usp=sharing)

Thanks

**Comment by JDL747** [comment]
Any feedback will be more than welcome as it's a bit blocking right now.

Thanks

**Comment by navaneetharaopy** [comment]
Hi, 

**For issue 1:**   
Please make sure your TV resolution is set at 720p(Since you have uploaded side images with dimension 320x540 ). 

Tv mode selection can be found under **Groups > Settings.**

![screen shot 2017-03-10 at 8 27 00 pm](https://cloud.githubusercontent.com/assets/6571626/23799941/654eb8ac-05d0-11e7-9178-0527cfbe656b.png)


![screen shot 2017-03-10 at 8 27 10 pm](https://cloud.githubusercontent.com/assets/6571626/23799949/6f0833be-05d0-11e7-94a1-5b21f6cbe93d.png)

**For issue 2 & Issue 3**
It would be great if you can attach a screenshot of your deployed playlist.


And Please provide details regrading
a) The type of raspberry pi used ( pi 3 , pi 2 OR pi b+ )
b) pisignage version used

**Comment by JDL747** [comment]
Deployed playlist :

![screen shot 2017-03-10 at 16 32 46](https://cloud.githubusercontent.com/assets/3844254/23801130/49680b14-05af-11e7-8f38-e64d25cf8977.png)

![screen shot 2017-03-10 at 16 33 06](https://cloud.githubusercontent.com/assets/3844254/23801133/4ba1a3fe-05af-11e7-86fe-c3e4782e7525.png)

------------

Raspberry pi : Pi 3 Model B
Pisignage version : 1.8.6

**Comment by colloqi** [comment]
Can I know your username at pisignage.com?

**Comment by JDL747** [comment]
festitv16

**Comment by JDL747** [comment]
Have you been able to find the issue?

**Comment by navaneetharaopy** [comment]
Hi, currently we are not able to reproduce the issue in our player. We tested our player with similar playlist , our player played all the contents as expected.
